/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tarefa8;

/**
 *
 * @author heito
 */
public class calculadora extends javax.swing.JFrame {

    double info1 = 0;
    double info2 = 0;
    double info3 = 0;
    String operacao = "";
    boolean podeApagar = false;

    /**
     * Creates new form calculadora
     */
    public calculadora() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jtfVisor = new javax.swing.JTextField();
        jB1 = new javax.swing.JButton();
        jB2 = new javax.swing.JButton();
        jB3 = new javax.swing.JButton();
        jB4 = new javax.swing.JButton();
        jB5 = new javax.swing.JButton();
        jB6 = new javax.swing.JButton();
        jB7 = new javax.swing.JButton();
        jB8 = new javax.swing.JButton();
        jB9 = new javax.swing.JButton();
        jB0 = new javax.swing.JButton();
        jBDividir = new javax.swing.JButton();
        jBMultiplicar = new javax.swing.JButton();
        jBSubtrair = new javax.swing.JButton();
        jBSomar = new javax.swing.JButton();
        jBIgual = new javax.swing.JButton();
        jBVirgula = new javax.swing.JButton();
        jBApagar = new javax.swing.JButton();
        jBApagarTudo = new javax.swing.JButton();
        subMemoria = new javax.swing.JButton();
        adMemoria = new javax.swing.JButton();
        armMemoria = new javax.swing.JButton();
        rechamarMemoria = new javax.swing.JButton();
        limparMmemoria = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPanel1KeyTyped(evt);
            }
        });
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jtfVisor.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jtfVisor.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtfVisor.setInheritsPopupMenu(true);
        jtfVisor.setMaximumSize(null);
        jtfVisor.setMinimumSize(null);
        jtfVisor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfVisorActionPerformed(evt);
            }
        });
        jtfVisor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfVisorKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.ipadx = 422;
        gridBagConstraints.ipady = 23;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 0, 0);
        jPanel1.add(jtfVisor, gridBagConstraints);

        jB1.setBackground(java.awt.Color.lightGray);
        jB1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jB1.setText("1");
        jB1.setMaximumSize(null);
        jB1.setMinimumSize(null);
        jB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 21;
        gridBagConstraints.ipady = 27;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 12, 0, 0);
        jPanel1.add(jB1, gridBagConstraints);

        jB2.setBackground(java.awt.Color.lightGray);
        jB2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jB2.setText("2");
        jB2.setMaximumSize(null);
        jB2.setMinimumSize(null);
        jB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 21;
        gridBagConstraints.ipady = 27;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 12, 0, 0);
        jPanel1.add(jB2, gridBagConstraints);

        jB3.setBackground(java.awt.Color.lightGray);
        jB3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jB3.setText("3");
        jB3.setMaximumSize(null);
        jB3.setMinimumSize(null);
        jB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 21;
        gridBagConstraints.ipady = 27;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 1, 0, 0);
        jPanel1.add(jB3, gridBagConstraints);

        jB4.setBackground(java.awt.Color.lightGray);
        jB4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jB4.setText("4");
        jB4.setMaximumSize(null);
        jB4.setMinimumSize(null);
        jB4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 21;
        gridBagConstraints.ipady = 27;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 12, 0, 0);
        jPanel1.add(jB4, gridBagConstraints);

        jB5.setBackground(java.awt.Color.lightGray);
        jB5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jB5.setText("5");
        jB5.setMaximumSize(null);
        jB5.setMinimumSize(null);
        jB5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB5ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 21;
        gridBagConstraints.ipady = 27;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 12, 0, 0);
        jPanel1.add(jB5, gridBagConstraints);

        jB6.setBackground(java.awt.Color.lightGray);
        jB6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jB6.setText("6");
        jB6.setMaximumSize(null);
        jB6.setMinimumSize(null);
        jB6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB6ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 21;
        gridBagConstraints.ipady = 27;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 1, 0, 0);
        jPanel1.add(jB6, gridBagConstraints);

        jB7.setBackground(java.awt.Color.lightGray);
        jB7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jB7.setText("7");
        jB7.setMaximumSize(null);
        jB7.setMinimumSize(null);
        jB7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB7ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 21;
        gridBagConstraints.ipady = 27;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(26, 12, 0, 0);
        jPanel1.add(jB7, gridBagConstraints);

        jB8.setBackground(java.awt.Color.lightGray);
        jB8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jB8.setText("8");
        jB8.setMaximumSize(null);
        jB8.setMinimumSize(null);
        jB8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB8ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 21;
        gridBagConstraints.ipady = 27;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(26, 12, 0, 0);
        jPanel1.add(jB8, gridBagConstraints);

        jB9.setBackground(java.awt.Color.lightGray);
        jB9.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jB9.setText("9");
        jB9.setMaximumSize(null);
        jB9.setMinimumSize(null);
        jB9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB9ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 21;
        gridBagConstraints.ipady = 27;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(26, 1, 0, 0);
        jPanel1.add(jB9, gridBagConstraints);

        jB0.setBackground(java.awt.Color.lightGray);
        jB0.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jB0.setText("0");
        jB0.setMaximumSize(null);
        jB0.setMinimumSize(null);
        jB0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB0ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 104;
        gridBagConstraints.ipady = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 12, 0, 0);
        jPanel1.add(jB0, gridBagConstraints);

        jBDividir.setBackground(new java.awt.Color(255, 255, 153));
        jBDividir.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jBDividir.setText("/");
        jBDividir.setMaximumSize(null);
        jBDividir.setMinimumSize(null);
        jBDividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDividirActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 52;
        gridBagConstraints.ipady = 27;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 18, 0, 0);
        jPanel1.add(jBDividir, gridBagConstraints);

        jBMultiplicar.setBackground(new java.awt.Color(255, 255, 153));
        jBMultiplicar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jBMultiplicar.setText("x");
        jBMultiplicar.setMaximumSize(null);
        jBMultiplicar.setMinimumSize(null);
        jBMultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMultiplicarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.ipadx = 48;
        gridBagConstraints.ipady = 27;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 18, 0, 0);
        jPanel1.add(jBMultiplicar, gridBagConstraints);

        jBSubtrair.setBackground(new java.awt.Color(255, 255, 153));
        jBSubtrair.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jBSubtrair.setText("-");
        jBSubtrair.setMaximumSize(null);
        jBSubtrair.setMinimumSize(null);
        jBSubtrair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSubtrairActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 51;
        gridBagConstraints.ipady = 27;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 18, 0, 0);
        jPanel1.add(jBSubtrair, gridBagConstraints);

        jBSomar.setBackground(new java.awt.Color(255, 255, 153));
        jBSomar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jBSomar.setText("+");
        jBSomar.setMaximumSize(null);
        jBSomar.setMinimumSize(null);
        jBSomar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSomarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.ipadx = 46;
        gridBagConstraints.ipady = 27;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 18, 25, 0);
        jPanel1.add(jBSomar, gridBagConstraints);

        jBIgual.setBackground(new java.awt.Color(153, 255, 255));
        jBIgual.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jBIgual.setText("=");
        jBIgual.setMaximumSize(null);
        jBIgual.setMinimumSize(null);
        jBIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBIgualActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 171;
        gridBagConstraints.ipady = 27;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 6, 25, 0);
        jPanel1.add(jBIgual, gridBagConstraints);

        jBVirgula.setBackground(java.awt.Color.lightGray);
        jBVirgula.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jBVirgula.setText(",");
        jBVirgula.setMaximumSize(null);
        jBVirgula.setMinimumSize(null);
        jBVirgula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVirgulaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 26, 0, 0);
        jPanel1.add(jBVirgula, gridBagConstraints);

        jBApagar.setBackground(new java.awt.Color(153, 153, 153));
        jBApagar.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jBApagar.setText("back space");
        jBApagar.setMaximumSize(null);
        jBApagar.setMinimumSize(null);
        jBApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBApagarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = -41;
        gridBagConstraints.ipady = -9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 18, 0, 0);
        jPanel1.add(jBApagar, gridBagConstraints);

        jBApagarTudo.setBackground(new java.awt.Color(153, 153, 153));
        jBApagarTudo.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jBApagarTudo.setText("c");
        jBApagarTudo.setMaximumSize(null);
        jBApagarTudo.setMinimumSize(null);
        jBApagarTudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBApagarTudoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 44;
        gridBagConstraints.ipady = -17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 18, 0, 0);
        jPanel1.add(jBApagarTudo, gridBagConstraints);

        subMemoria.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        subMemoria.setText("m-");
        subMemoria.setMaximumSize(null);
        subMemoria.setMinimumSize(null);
        subMemoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMemoriaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 34;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 12, 0, 0);
        jPanel1.add(subMemoria, gridBagConstraints);

        adMemoria.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        adMemoria.setText("m+");
        adMemoria.setMaximumSize(null);
        adMemoria.setMinimumSize(null);
        adMemoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adMemoriaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 29;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 0, 0);
        jPanel1.add(adMemoria, gridBagConstraints);

        armMemoria.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        armMemoria.setText("ms");
        armMemoria.setMaximumSize(null);
        armMemoria.setMinimumSize(null);
        armMemoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                armMemoriaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(24, 12, 0, 0);
        jPanel1.add(armMemoria, gridBagConstraints);

        rechamarMemoria.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        rechamarMemoria.setText("mr");
        rechamarMemoria.setEnabled(false);
        rechamarMemoria.setMaximumSize(null);
        rechamarMemoria.setMinimumSize(null);
        rechamarMemoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rechamarMemoriaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.ipadx = 33;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 12, 25, 0);
        jPanel1.add(rechamarMemoria, gridBagConstraints);

        limparMmemoria.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        limparMmemoria.setText("mc");
        limparMmemoria.setEnabled(false);
        limparMmemoria.setMaximumSize(null);
        limparMmemoria.setMinimumSize(null);
        limparMmemoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparMmemoriaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 12, 0, 0);
        jPanel1.add(limparMmemoria, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel1.getAccessibleContext().setAccessibleName("calc.prototipo\n");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfVisorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfVisorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfVisorActionPerformed

    private void jB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB2ActionPerformed
        setNumeroVisor("2");
    }//GEN-LAST:event_jB2ActionPerformed

    private void jB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB3ActionPerformed
        setNumeroVisor("3");
    }//GEN-LAST:event_jB3ActionPerformed

    private void jB4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB4ActionPerformed
        setNumeroVisor("4");
    }//GEN-LAST:event_jB4ActionPerformed

    private void jB5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB5ActionPerformed
        setNumeroVisor("5");
    }//GEN-LAST:event_jB5ActionPerformed

    private void jB6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB6ActionPerformed
        setNumeroVisor("6");
    }//GEN-LAST:event_jB6ActionPerformed

    private void jB7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB7ActionPerformed
        setNumeroVisor("7");
    }//GEN-LAST:event_jB7ActionPerformed

    private void jB8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB8ActionPerformed
        setNumeroVisor("8");
    }//GEN-LAST:event_jB8ActionPerformed

    private void jB9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB9ActionPerformed
        setNumeroVisor("9");
    }//GEN-LAST:event_jB9ActionPerformed

    private void jB0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB0ActionPerformed
        setNumeroVisor("0");
    }//GEN-LAST:event_jB0ActionPerformed

    private void jBDividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDividirActionPerformed

        preCalculo("/");


    }//GEN-LAST:event_jBDividirActionPerformed

    private void jBMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMultiplicarActionPerformed

        preCalculo("x");


    }//GEN-LAST:event_jBMultiplicarActionPerformed

    private void jBSubtrairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSubtrairActionPerformed

        preCalculo("-");


    }//GEN-LAST:event_jBSubtrairActionPerformed

    private void jBSomarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSomarActionPerformed

        preCalculo("+");

    }//GEN-LAST:event_jBSomarActionPerformed

    private void jBIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBIgualActionPerformed

        
        calculo();
    }//GEN-LAST:event_jBIgualActionPerformed

    private void jB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB1ActionPerformed
        setNumeroVisor("1");

    }//GEN-LAST:event_jB1ActionPerformed

    private void jtfVisorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfVisorKeyTyped
        char c = evt.getKeyChar();
        if (!verificaLetra(c)) {
            evt.consume();
        } else {
            if (c == '*') {
                c = 'x';
            }
            if (c == ',') {
                insereVirgula();
                evt.consume();
            } else {
                String textoPronto = jtfVisor.getText() + c;
                jtfVisor.setText(textoPronto);
                evt.consume();
            }
            if (jtfVisor.getText().isEmpty()) {
                preCalculo(operacao);
                calculo();

            }

        }


    }//GEN-LAST:event_jtfVisorKeyTyped

    private void jPanel1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel1KeyTyped

    }//GEN-LAST:event_jPanel1KeyTyped

    private void jBVirgulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVirgulaActionPerformed
        //setNumeroVisor(",");
        insereVirgula();
    }//GEN-LAST:event_jBVirgulaActionPerformed

    private void jBApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBApagarActionPerformed
        apagar();
    }//GEN-LAST:event_jBApagarActionPerformed

    private void limparMmemoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparMmemoriaActionPerformed
        info3 = 0;
        apagarTudo();
        limparMmemoria.setEnabled(false);
        rechamarMemoria.setEnabled(false);


    }//GEN-LAST:event_limparMmemoriaActionPerformed

    private void subMemoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMemoriaActionPerformed
        if (operacao.equals("") && !jtfVisor.getText().isEmpty()) {
            info3 = info3 - Double.parseDouble(jtfVisor.getText());
        }
    }//GEN-LAST:event_subMemoriaActionPerformed

    private void adMemoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adMemoriaActionPerformed

        if (operacao.equals("") && !jtfVisor.getText().isEmpty()) {
            info3 = Double.parseDouble(jtfVisor.getText()) + info3;
        }

    }//GEN-LAST:event_adMemoriaActionPerformed

    private void armMemoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_armMemoriaActionPerformed
        salvaMemoria();
    }//GEN-LAST:event_armMemoriaActionPerformed

    private void rechamarMemoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rechamarMemoriaActionPerformed

        jtfVisor.setText(String.valueOf(info3));

    }//GEN-LAST:event_rechamarMemoriaActionPerformed

    private void jBApagarTudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBApagarTudoActionPerformed
        // TODO add your handling code here:
        apagarTudo();


    }//GEN-LAST:event_jBApagarTudoActionPerformed

    public void setNumeroVisor(String numero) {
        if (podeApagar) {
            jtfVisor.setText("");
            podeApagar = false;
        }
        jtfVisor.setText(jtfVisor.getText() + numero);
    }

    public void salvaMemoria() {
        if (!jtfVisor.getText().isEmpty()) {
            info3 = Double.parseDouble(jtfVisor.getText().replaceAll(",", "."));
            rechamarMemoria.setEnabled(true);
            limparMmemoria.setEnabled(true);

        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adMemoria;
    private javax.swing.JButton armMemoria;
    private javax.swing.JButton jB0;
    private javax.swing.JButton jB1;
    private javax.swing.JButton jB2;
    private javax.swing.JButton jB3;
    private javax.swing.JButton jB4;
    private javax.swing.JButton jB5;
    private javax.swing.JButton jB6;
    private javax.swing.JButton jB7;
    private javax.swing.JButton jB8;
    private javax.swing.JButton jB9;
    private javax.swing.JButton jBApagar;
    private javax.swing.JButton jBApagarTudo;
    private javax.swing.JButton jBDividir;
    private javax.swing.JButton jBIgual;
    private javax.swing.JButton jBMultiplicar;
    private javax.swing.JButton jBSomar;
    private javax.swing.JButton jBSubtrair;
    private javax.swing.JButton jBVirgula;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jtfVisor;
    private javax.swing.JButton limparMmemoria;
    private javax.swing.JButton rechamarMemoria;
    private javax.swing.JButton subMemoria;
    // End of variables declaration//GEN-END:variables

    private boolean verificaLetra(char c) {
        String bancoDados = "0123456789,+-*/";
        if (bancoDados.contains(String.valueOf(c))) {
            return true;
        }
        return false;
    }

    private void insereVirgula() {
        if (jtfVisor.getText().isEmpty()) {
            setNumeroVisor("0,");
        } else if (!jtfVisor.getText().contains(",")) {
            setNumeroVisor(",");
        }
    }

    private void apagarTudo() {
        if (jtfVisor.getText().isEmpty()) {
        } else {
            jtfVisor.setText(null);
            operacao = "";
        }

    }

    private void apagar() {
        String apagar = jtfVisor.getText();
        StringBuilder back = new StringBuilder(apagar);
        if (!jtfVisor.getText().isEmpty()) {
            apagar = String.valueOf(back.deleteCharAt(apagar.length() - 1));
            jtfVisor.setText(apagar);
        }
    }

    private void calculo() {
        try{
        if (jtfVisor.getText().isEmpty()) {
        } else {
            info2 = Double.parseDouble(jtfVisor.getText().replaceAll(",", "."));
            if (operacao.equals("+")) {
                jtfVisor.setText(String.valueOf(info1 + info2));
            }
            if (operacao.equals("-")) {
                jtfVisor.setText(String.valueOf(info1 - info2));
            }
            if (operacao.equals("/")) {
                jtfVisor.setText(String.valueOf(info1 / info2));
            }
            if (operacao.equals("x")) {
                jtfVisor.setText(String.valueOf(info1 * info2));
            }
            operacao = "";
            info1 = Double.parseDouble(jtfVisor.getText().replaceAll(",", "."));
            podeApagar = true;
        }
    }catch(NumberFormatException e){
        }
    }

    private void preCalculo(String op) {
        if (jtfVisor.getText().isEmpty()) {
        } else {
            if (operacao.equals("")) {
                info1 = Double.parseDouble(jtfVisor.getText().replaceAll(",", "."));
                operacao = op;
                setNumeroVisor(op);
                podeApagar = true;
            } else {
                String lastChar = jtfVisor.getText();
                lastChar = lastChar.substring(lastChar.length() -1, lastChar.length());
                if (lastChar.contains("+ / - x")) {
                    apagar();
                    info1 = Double.parseDouble(jtfVisor.getText().replaceAll(",", "."));
                    operacao = op;
                    podeApagar = false;
                    setNumeroVisor(op);
                    podeApagar = true;
                } else {
                    calculo();
                    operacao = op;
                }
            }
        }
    }

}
